export const universities = [
  // "Abubakar Tafawa Balewa University (ATBU)",
  // "Ahmadu Bello University (ABU)",
  // "Bayero University (BUK)",
  // "Federal University, Birnin Kebbi (FUBK)",
  // "Federal University, Dutsin-Ma (FUDM)",
  // "Federal University, Dutse (FUD)",
  // "Federal University, Gashua (FUG)",
  // "Federal University, Gusau (FUGUS)",
  // "Federal University, Kashere (FUK)",
  // "Federal University, Lafia (FULAFIA)",
  // "Federal University, Lokoja (FUL)",
  // "Federal University, Otuoke (FUO)",
  // "Federal University, Oye Ekiti (FUOYE)",
  // "Federal University of Agriculture, Abeokuta (FUNAAB)",
  // "Federal University of Agriculture, Makurdi (FUAM)",
  // "Federal University of Health Sciences, Azare (FUHSA)",
  // "Federal University of Technology, Akure (FUTA)",
  // "Federal University of Technology, Minna (FUTMINNA)",
  // "Federal University of Technology, Owerri (FUTO)",
  // "Federal University of Petroleum Resources, Effurun (FUPRE)",
  // "Michael Okpara University of Agriculture, Umudike (MOUAU)",
  // "Modibo Adama University of Technology, Yola (MAUTECH)",
  // "National Open University of Nigeria (NOUN)",
  // "Nnamdi Azikiwe University (UNIZIK)",
  "University of Benin (UNIBEN)",
  // "University of Ibadan (UI)",
  // "University of Ilorin (UNILORIN)",
  // "University of Jos (UNIJOS)",
  // "University of Lagos (UNILAG)",
  // "University of Nigeria, Nsukka (UNN)",
  // "Usmanu Danfodiyo University, Sokoto (UDUS)",
];

export const faculties = [
  {
    name: "Faculty of Agriculture",
    departments: [
      "Agricultural Economics and Extension",
      "Animal Science",
      "Crop Science",
      "Fisheries",
      "Forestry and Wildlife",
      "Soil Science",
    ],
  },
  {
    name: "Faculty of Arts",
    departments: [
      "English and Literature",
      "Fine and Applied Arts",
      "Foreign Languages",
      "History and International Studies",
      "Linguistics Studies",
      "Mass Communication",
      "Philosophy",
      "Religions",
      "Theatre Arts",
    ],
  },
  {
    name: "Faculty of Basic Medical Sciences",
    departments: [
      "Anatomy",
      "Medical Biochemistry",
      "Medical Laboratory Science",
      "Nursing Science",
      "Physiology",
      "Physiotherapy",
      "Radiography and Radiation Science",
    ],
  },
  {
    name: "Faculty of Dentistry",
    departments: [
      "Child Dental Health",
      "Oral and Maxillofacial Surgery",
      "Preventive Dentistry",
      "Restorative Dentistry",
    ],
  },
  {
    name: "Faculty of Education",
    departments: [
      "Curriculum and Instructional Technology",
      "Educational Foundations",
      "Educational Management",
      "Educational Psychology and Curriculum Studies",
      "Health, Safety, and Environmental Education",
      "Human Kinetics and Sports Science",
      "Vocational and Technical Education",
    ],
  },
  {
    name: "Faculty of Engineering",
    departments: [
      "Chemical Engineering",
      "Civil Engineering",
      "Electrical and Electronics Engineering",
      "Mechanical Engineering",
      "Petroleum Engineering",
      "Production Engineering",
      "Agricultural Engineering",
      "Marine Engineering",
    ],
  },
  {
    name: "Faculty of Environmental Sciences",
    departments: [
      "Architecture",
      "Estate Management",
      "Geography and Regional Planning",
      "Quantity Surveying",
      "Surveying and Geoinformatics",
      "Urban and Regional Planning",
    ],
  },
  {
    name: "Faculty of Law",
    departments: [
      "Commercial and Industrial Law",
      "Jurisprudence and International Law",
      "Public Law",
    ],
  },
  {
    name: "Faculty of Life Sciences",
    departments: [
      "Animal and Environmental Biology",
      "Biochemistry",
      "Microbiology",
      "Optometry",
      "Plant Biology and Biotechnology",
      "Environmental Management and Toxicology",
      "Science Laboratory Technology",
    ],
  },
  {
    name: "Faculty of Management Sciences",
    departments: [
      "Accounting",
      "Actuarial Science",
      "Banking and Finance",
      "Business Administration",
      "Entrepreneurship",
      "Finance",
      "Human Resource Management",
      "Insurance",
      "Marketing",
    ],
  },
  {
    name: "Faculty of Pharmacy",
    departments: [
      "Clinical Pharmacy",
      "Pharmaceutical Chemistry",
      "Pharmaceutical Microbiology",
      "Pharmacognosy",
      "Pharmacology",
      "Social and Administrative Pharmacy",
    ],
  },
  {
    name: "Faculty of Physical Sciences",
    departments: [
      "Chemistry",
      "Computer Science",
      "Geology",
      "Mathematics",
      "Physics",
      "Statistics",
    ],
  },
  {
    name: "Faculty of Social Sciences",
    departments: [
      "Economics",
      "Geography and Disaster Risk Management",
      "Library and Information Science",
      "Peace Studies and Conflict Resolution",
      "Political Science",
      "Public Administration",
      "Sociology and Anthropology",
      "Social Work",
    ],
  },
  {
    name: "Faculty of Veterinary Medicine",
    departments: [
      "Animal Health and Production",
      "Veterinary Anatomy",
      "Veterinary Medicine",
      "Veterinary Microbiology and Parasitology",
      "Veterinary Pathology",
      "Veterinary Physiology and Pharmacology",
      "Veterinary Public Health and Preventive Medicine",
    ],
  },
  {
    name: "Faculty of Science Laboratory Technology",
    departments: [
      "Analytical Chemistry",
      "Biochemistry",
      "Environmental Science",
      "Industrial Chemistry",
    ],
  },
  {
    name: "Faculty of Nursing Sciences",
    departments: [
      "Public Health Nursing",
      "Mental Health Nursing",
      "Medical-Surgical Nursing",
      "Maternal and Child Health Nursing",
    ],
  },
];

export const BANKS = [
  "Access Bank",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "Guaranty Trust Bank (GTB)",
  "United Bank for Africa (UBA)",
  "Zenith Bank",
  "Stanbic IBTC",
  "Ecobank",
  "FCMB",
  "Polaris Bank",
  "Providus Bank",
  "Wema Bank",
  "Sterling Bank",
  "Unity Bank",
];
